requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution_like "opensuse" }}
- zypper in -y git
{{else if eq .Values.distribution "fedora" }}
- dnf install -y git
{{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y git
{{end}}
{{end}}
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\+*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/rancher/rancherd
steps:
- |
   cd rancherd && \
   ./scripts/build && \
   cp bin/rancherd /usr/bin/rancherd && \
   cp rancherd.service /usr/lib/systemd/system/rancherd.service
includes:
- /usr/bin/rancherd
- /usr/lib/systemd/system/rancherd.service
